#!/bin/sh -x
# create snapshots from git commits

srctree=~/DATA_SOURCES/linux-3.git
srctag=v2.6.12
topcommit=master
dir=`basename $srctree`-clone

btrfs='sudo btrfs'

if ! [ -d $dir ]; then
	echo cloning full tree
	$btrfs subvol del $dir-temp
	$btrfs subvol create $dir-temp
	git clone $srctree $dir
else
	echo using existing tree
fi

mv $dir-temp $dir
cd $dir
git rev-list $srctag..$topcommit > ../rev-list

for i in $(cat ../rev-list); do
	git checkout -b test-$i $i
	$btrfs subvol snap . ../snap-$i
done
