#!/bin/sh -x
# create snapshots from git commits

srctree=~/DATA_SOURCES/linux-3.git
srctag=v2.6.12
topcommit=master
dir=`basename $srctree`-clone

skipexisting=true
sortrevs=false

btrfs='sudo btrfs'

if ! [ -d $dir ]; then
	echo cloning full tree
	$btrfs subvol del $dir-temp
	$btrfs subvol create $dir-temp
	git clone $srctree $dir-temp
else
	echo using existing tree
fi

mv $dir-temp $dir
cd $dir
git rev-list $srctag..$topcommit | { $sortrevs && sort || cat; } > ../rev-list

for i in $(cat ../rev-list); do
	$skipexisting && [ -d snap-$i ] && continue
	git checkout -f -b test-$i $i
	$btrfs subvol snap . ../snap-$i
done
