#!/bin/bash

num=$1
fsx=./fsx

if [ "x$num" == "x" ]; then
    num=50
fi

echo "using $num procs"

for x in `seq 1 $num` ; do
    echo -n "$x "
    $fsx -q xxxf$x -Z -R -W -r 4096 -w 4096 &
done
echo "waiting"
wait

