#!/bin/sh
# Message-ID: <515B838A.7020000@jp.fujitsu.com>
# When inode_cache was specified for the mount option, I encountered the
# following messages at umount.

mkfs.btrfs -f /dev/sdc4
mount -o compress=lzo,autodefrag,inode_cache /dev/sdc4 /test1
dd if=/dev/zero of=/test1/file1 bs=1M count=8192
dd if=/test1/file1 of=/dev/null bs=1M
rm -f /test1/file1
umount /test1
