#!/bin/sh
# interactive sleep

trap "{ echo; exit 1; }" SIGINT

delay=${1:-1}
i=0
while test $i -lt $delay;do
	sleep 1
	i=$(expr $i + 1)
	ii=$(expr $i % 10)
	if test $(expr $i % 10) = 0; then
		echo -n "{$i}"
	else
		echo -n $ii
	fi
done
echo
